### PR TITLE
fix segfault in interface

### LINKED ISSUE #702: Segfault in interface
**Describe the bug**
Segfault in the visual interface. (interface/widgets/widget.cpp), mousepressEvent function has world()->getworld().us. This pointer is dead on startup.

**To Reproduce**
Open an AI without an available world state. 
Click multiple times on the field

**Expected behavior**
Don't crash?

### PR DESCRIPTION
**Pull request by mrlukasbos**
fixes #702

### CODE REVIEW

File: src/world/World.cpp [hunk 1]
```diff
@@ -104,8 +104,7 @@ bool World::weHaveRobots() {
 
 const WorldData World::getWorld() {
     std::lock_guard<std::mutex> lock(worldMutex);
-    auto thing = WorldData(*worldDataPtr);
-    return thing;
+    return WorldData(*worldDataPtr);
```
Comment (mrlukasbos) [inline src/world/World.cpp]: couldnt resist
