### PR TITLE
Feature/fix receive defense area

### LINKED ISSUE #452: Receive should not pick receive points in the defence area's during normal play.
It does do this. Can probably just pick points on the line segment parts that are close but not in the defence area.

### PR DESCRIPTION
**Pull request by rolfvdhulst**
Needs the polygon and line classes in roboteam_utils to work, but fixes an important bug in field.

This PR fixes receiving going into the defense area.
fixes #452

### CODE REVIEW

File: roboteam_ai/src/skills/Receive.cpp [hunk 1]
```diff
@@ -14,7 +15,7 @@ Receive::Receive(string name, bt::Blackboard::Ptr blackboard) : Skill(std::move(
 
 void Receive::onInitialize() {
     readyToPassSet = false;
-   // basicGtp.setCanMoveInDefenseArea(false);
+    canMoveInDefenseArea=properties->getBool("canMoveInDefenseArea");
```
Comment (mrlukasbos) [inline roboteam_ai/src/skills/Receive.cpp]: this boolean should actually be dependent on refstate!

File: roboteam_ai/src/skills/Receive.cpp [hunk 2]
```diff
@@ -62,9 +63,37 @@ void Receive::onTerminate(Status s) {
...
 Vector2 Receive::computeInterceptPoint(const Vector2& startBall, const Vector2& endBall) {
-    return robot->pos.project(startBall, endBall);
-}
+    double margin = 0.3;
+    Vector2 projectPos = Line(startBall,endBall).project(robot->pos);
+    if (canMoveInDefenseArea) {
+        return projectPos;
+    }
+    if (world::field->pointIsInDefenceArea(projectPos, true, margin)||world::field->pointIsInDefenceArea(projectPos, false, margin)) {
+        Polygon dUs(world::field->getDefenseArea(false, margin)), dThem(world::field->getDefenseArea(true, margin));
```
Comment (mrlukasbos) [inline roboteam_ai/src/skills/Receive.cpp]: `dUs `is a weird name?

File: roboteam_ai/src/skills/Receive.cpp [hunk 3]
```diff
@@ -62,9 +63,37 @@ void Receive::onTerminate(Status s) {
...
+        interface::Input::drawData(interface::DEBUG,world::field->getDefenseArea(false, margin),Qt::red,-1,interface::Drawing::LINES_CONNECTED);
```
Comment (mrlukasbos) [inline roboteam_ai/src/skills/Receive.cpp]: we should probably always draw this thing on debug, but we should move it to the interface

File: roboteam_ai/src/skills/Receive.cpp (hunk 1 above)
Comment (rolfvdhulst) [reply roboteam_ai/src/skills/Receive.cpp]: Could be, but we could also manually set it in the relevant trees that change based on refState regardless.

Comment (rolfvdhulst) [reply roboteam_ai/src/skills/Receive.cpp]: I think that is probably easier.

File: roboteam_ai/src/skills/Receive.cpp (hunk 2 above)
Comment (rolfvdhulst) [reply roboteam_ai/src/skills/Receive.cpp]: refactored to defUs

File: roboteam_ai/src/skills/Receive.cpp (hunk 3 above)
Comment (rolfvdhulst) [reply roboteam_ai/src/skills/Receive.cpp]: I removed it from here now, since we use a lot of different margins.

File: roboteam_ai/src/skills/Receive.cpp (hunk 2 above)
Comment (ThijsLuttikhuis) [reply roboteam_ai/src/skills/Receive.cpp]: dusssss

Comment (ThijsLuttikhuis) [reply roboteam_ai/src/skills/Receive.cpp]: dthemmmm

Comment (ThijsLuttikhuis) [reply roboteam_ai/src/skills/Receive.cpp]: please initialize the two polygons on seperate lines

File: roboteam_ai/src/skills/Receive.cpp [hunk 4]
```diff
@@ -69,22 +69,24 @@ Vector2 Receive::computeInterceptPoint(const Vector2& startBall, const Vector2&
         return projectPos;
     }
     if (world::field->pointIsInDefenceArea(projectPos, true, margin)||world::field->pointIsInDefenceArea(projectPos, false, margin)) {
-        Polygon dUs(world::field->getDefenseArea(false, margin)), dThem(world::field->getDefenseArea(true, margin));
-        interface::Input::drawData(interface::DEBUG,world::field->getDefenseArea(false, margin),Qt::red,-1,interface::Drawing::LINES_CONNECTED);
+        Polygon defUs(world::field->getDefenseArea(true, margin));
```
Comment (ThijsLuttikhuis) [inline roboteam_ai/src/skills/Receive.cpp]: still wrong name

File: roboteam_ai/src/skills/Receive.cpp [hunk 5]
```diff
@@ -62,9 +63,39 @@ void Receive::onTerminate(Status s) {
...
 Vector2 Receive::computeInterceptPoint(const Vector2& startBall, const Vector2& endBall) {
-    return robot->pos.project(startBall, endBall);
-}
+    double margin = 0.3;
+    Vector2 projectPos = Line(startBall,endBall).project(robot->pos);
+    if (canMoveInDefenseArea) {
+        return projectPos;
+    }
+    if (world::field->pointIsInDefenceArea(projectPos, true, margin)||world::field->pointIsInDefenceArea(projectPos, false, margin)) {
+        Polygon defenceAreaUs(world::field->getDefenseArea(true, margin));
```
Comment (ThijsLuttikhuis) [inline roboteam_ai/src/skills/Receive.cpp]: perfect

File: roboteam_ai/src/skills/Receive.cpp (hunk 1 above)
Comment (mrlukasbos) [reply roboteam_ai/src/skills/Receive.cpp]: but also more prone to errors. Just keep it for now, in another branch I am redesigning the application of rules anyway
