### PR TITLE
Fix free kick and penalty for 8 robots

### LINKED ISSUE #506: Free kick formation does not work with 8 robots
The free kick formation only works with 7 robots or less. otherwise it gives the error: wrong input for hungarian: more robots than positions

### PR DESCRIPTION
**Pull request by Barisimre**
Fixes #506

### CODE REVIEW

File: roboteam_ai/src/Switches.cpp [hunk 1]
```diff
@@ -496,7 +498,8 @@ bt::Node::Ptr Switches::tacticSwitch(std::string name, bt::Blackboard::Ptr prope
                     {"line2", robotType::RANDOM},
                     {"line4", robotType::RANDOM},
                     {"line5", robotType::RANDOM},
-                    {"line3", robotType::RANDOM}
+                    {"line3", robotType::RANDOM},
```
Comment (ThijsLuttikhuis) [inline roboteam_ai/src/Switches.cpp]: why is this not in order?
