### PR TITLE
Fix/stp improved kick chip speed

### LINKED ISSUE #932: determineChipForce needs a refactor
(ChipAtPos.cpp, determineChipForce())

### LINKED ISSUE #933: determineKickForce needs a refactor
(KickAtPos.cpp, determineKickForce())

### PR DESCRIPTION
**Pull request by timovdk**
Improved the way the kick and chip speed are calculated. There is still a lot to do tuning-wise but that is out of scope for this PR..
Closes #932, closes #933

### CODE REVIEW

File: src/stp/new_plays/Pass.cpp [hunk 1]
```diff
@@ -76,8 +79,12 @@ void Pass::calculateInfoForRoles() noexcept {
 
 std::vector<Vector2> Pass::calculateDefensivePositions(int numberOfDefenders, world_new::World* world, std::vector<world_new::view::RobotView> enemyRobots) {
     std::vector<Vector2> positions = {};
+
     // 3 robots will defend goal
     for (int i = 0; i < numberOfDefenders; i++) {
+        std::stringstream strstr;
+        strstr << "text" << i + 1;
+        std::string x = strstr.str();
```
Comment (timovdk) [inline src/stp/new_plays/Pass.cpp]:
```suggestion
```

File: src/stp/new_tactics/ChipAtPos.cpp [hunk 2]
```diff
@@ -38,52 +38,45 @@ StpInfo ChipAtPos::calculateInfoForSkill(StpInfo const &info) noexcept {
...
+    }
+
+    // TODO: TUNE this function might need to change
+    // TODO: TUNE chip related constants might need tuning
+    // Calculate the velocity based on this function with the previously set limitingFactor
+    auto velocity = sqrt(distance) * Constants::MAX_CHIP_POWER() / (sqrt(Constants::MAX_POWER_CHIP_DISTANCE()) * limitingFactor);
 
-    // limit the output to the max chip speed
-    return std::min(std::max(velocity, 1.01), rtt::ai::Constants::MAX_KICK_POWER());
+    // Make sure velocity is always between 1.01 and MAX_CHIP_POWER
```
Comment (timovdk) [inline src/stp/new_tactics/ChipAtPos.cpp]:
```suggestion
    // Make sure velocity is always between MIN_CHIP_POWER and MAX_CHIP_POWER
```

File: src/stp/new_tactics/KickAtPos.cpp [hunk 3]
```diff
@@ -49,44 +49,37 @@ StpInfo KickAtPos::calculateInfoForSkill(StpInfo const &info) noexcept {
...
+    }
+
+    // TODO: TUNE this function might need to change
+    // TODO: TUNE kick related constants (in Constants.h) might need tuning
+    // Calculate the velocity based on this function with the previously set limitingFactor
+    auto velocity = sqrt(distance) * Constants::MAX_KICK_POWER() / (sqrt(Constants::MAX_POWER_KICK_DISTANCE()) * limitingFactor);
 
-    // limit the output to the max kick speed
-    return std::min(std::max(velocity, 1.01), rtt::ai::Constants::MAX_KICK_POWER());
+    // Make sure velocity is always between 1.01 and MAX_KICK_POWER
```
Comment (timovdk) [inline src/stp/new_tactics/KickAtPos.cpp]:
```suggestion
    // Make sure velocity is always between MIN_KICK_POWER and MAX_KICK_POWER
```

File: include/roboteam_ai/stp/StpInfo.h [hunk 4]
```diff
@@ -71,9 +71,10 @@ struct Areas {
         return std::any_of(areasToAvoid.begin(), areasToAvoid.end(), [&](auto const& area) { return area.intersects(circle); });
     }
 };
+
 const int blockLength = 3; // The number of elements in the blockdistance enum
 enum BlockDistance { CLOSE = 1, HALFWAY, FAR }; // If you change this be sure to change blocklength also
-enum KickChipType { DRIBBLE_KICK, BALL_PLACEMENT, PASS, MAX_SPEED };
+enum KickChipType { PASS, TARGET, MAX };
```
Comment (RobotJente) [inline include/roboteam_ai/stp/StpInfo.h:77]: what is target?

**Review by RobotJente — APPROVED** [review]

File: include/roboteam_ai/stp/StpInfo.h (hunk 4 above)
Comment (timovdk) [reply include/roboteam_ai/stp/StpInfo.h:77]: That it tries to have the ball still at the shoot position, instead of overshooting a bit like you do when passing

File: src/stp/new_tactics/ChipAtPos.cpp [hunk 5]
```diff
@@ -38,52 +38,45 @@ StpInfo ChipAtPos::calculateInfoForSkill(StpInfo const &info) noexcept {
...
+
+    // TODO: TUNE this function might need to change
+    // TODO: TUNE chip related constants might need tuning
+    // Calculate the velocity based on this function with the previously set limitingFactor
+    auto velocity = sqrt(distance) * Constants::MAX_CHIP_POWER() / (sqrt(Constants::MAX_POWER_CHIP_DISTANCE()) * limitingFactor);
 
-    // limit the output to the max chip speed
-    return std::min(std::max(velocity, 1.01), rtt::ai::Constants::MAX_KICK_POWER());
+    // Make sure velocity is always between MIN_CHIP_POWER and MAX_CHIP_POWER
+    return std::min(std::max(velocity, Constants::MIN_CHIP_POWER()), Constants::MAX_CHIP_POWER());
```
Comment (timovdk) [inline src/stp/new_tactics/ChipAtPos.cpp]: This can be std::clamp, oops

File: src/stp/new_tactics/KickAtPos.cpp [hunk 6]
```diff
@@ -49,44 +49,37 @@ StpInfo KickAtPos::calculateInfoForSkill(StpInfo const &info) noexcept {
...
+
+    // TODO: TUNE this function might need to change
+    // TODO: TUNE kick related constants (in Constants.h) might need tuning
+    // Calculate the velocity based on this function with the previously set limitingFactor
+    auto velocity = sqrt(distance) * Constants::MAX_KICK_POWER() / (sqrt(Constants::MAX_POWER_KICK_DISTANCE()) * limitingFactor);
 
-    // limit the output to the max kick speed
-    return std::min(std::max(velocity, 1.01), rtt::ai::Constants::MAX_KICK_POWER());
+    // Make sure velocity is always between MIN_KICK_POWER and MAX_KICK_POWER
+    return std::min(std::max(velocity, Constants::MIN_KICK_POWER()), Constants::MAX_KICK_POWER());
```
Comment (timovdk) [inline src/stp/new_tactics/KickAtPos.cpp]: std::clamp
