### PR TITLE
Feature/fix robot dealer test

### LINKED ISSUE #61: Robot Dealer Tests
Create (working) tests for the robot dealer.

### PR DESCRIPTION
**Pull request by rolfvdhulst**
- [ ] The tests are passing

### Summary
Fixes a lot of tests that were failing, not compiling, mostly because of the Robot Dealer interactions. Also some minor bugfixes, and removed a redundant skill. All tests are working now.

fixes #61

**functionality**  
- Is the code is properly tested?
- Is the code working as expected
- Is the code is understandable and easy to read
- Are proper abstractions made? (no duplicate code, nice use of functions/objects)

**style**  
- Variables/objects/classes have proper names
- Proper use of variables: nu unused vars, no magic numbers
- No possible memory leaks. Mutexes properly used when multithreading? possible pointer issues?
- Are smart pointers used?
- unused variables?
- magic numbers?
- well documented?
- No unused imports?
- No leftover code / unused comments
- Proper indentation
- Proper use of namespaces

### CODE REVIEW

File: roboteam_ai/src/conditions/IsInDefenseArea.cpp [hunk 1]
```diff
@@ -12,17 +12,34 @@ IsInDefenseArea::IsInDefenseArea(std::string name, bt::Blackboard::Ptr blackboar
...
+        robot = getRobotFromProperties(properties);
+        if (robot) {
+            point = robot->pos;
+        }
+        else{
+            return Status::Failure;
+        }
+    }
+    else{
+        //TODO: Fix this once ball PR is merged.
```
Comment (mrlukasbos) [inline roboteam_ai/src/conditions/IsInDefenseArea.cpp]: todo
